export default [
  { description: 'Acre', slug: 'AC', id: 'Acre' },
  { description: 'Alagoas', slug: 'AL', id: 'Alagoas' },
  { description: 'Amapá', slug: 'AP', id: 'Amapá' },
  { description: 'Amazonas', slug: 'AM', id: 'Amazonas' },
  { description: 'Bahia', slug: 'BA', id: 'Bahia' },
  { description: 'Ceará', slug: 'CE', id: 'Ceará' },
  { description: 'Distrito Federal', slug: 'DF', id: 'Distrito Federal' },
  { description: 'Espírito Santo', slug: 'ES', id: 'Espírito Santo' },
  { description: 'Goiás', slug: 'GO', id: 'Goiás' },
  { description: 'Maranhão', slug: 'MA', id: 'Maranhão' },
  { description: 'Mato Grosso', slug: 'MT', id: 'Mato Grosso' },
  { description: 'Mato Grosso do Sul', slug: 'MS', id: 'Mato Grosso do Sul' },
  { description: 'Minas Gerais', slug: 'MG', id: 'Minas Gerais' },
  { description: 'Pará', slug: 'PA', id: 'Pará' },
  { description: 'Paraíba', slug: 'PB', id: 'Paraíba' },
  { description: 'Paraná', slug: 'PR', id: 'Paraná' },
  { description: 'Pernambuco', slug: 'PE', id: 'Pernambuco' },
  { description: 'Piauí', slug: 'PI', id: 'Piauí' },
  { description: 'Rio de Janeiro', slug: 'RJ', id: 'Rio de Janeiro' },
  { description: 'Rio Grande do Norte', slug: 'RN', id: 'Rio Grande do Norte' },
  { description: 'Rio Grande do Sul', slug: 'RS', id: 'Rio Grande do Sul' },
  { description: 'Rondônia', slug: 'RO', id: 'Rondônia' },
  { description: 'Roraima', slug: 'RR', id: 'Roraima' },
  { description: 'Santa Catarina', slug: 'SC', id: 'Santa Catarina' },
  { description: 'São Paulo', slug: 'SP', id: 'São Paulo' },
  { description: 'Sergipe', slug: 'SE', id: 'Sergipe' },
  { description: 'Tocantins', slug: 'TO', id: 'Tocantins' },
];
